# Generated by Django 3.2.4 on 2023-01-24 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_message_receiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='reaction',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
