# Generated by Django 3.2.4 on 2023-01-25 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_message_reaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='reaction',
        ),
    ]
