# Generated by Django 3.2.4 on 2023-01-26 11:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0006_remove_message_reaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageroom',
            name='users_active',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
