# Generated by Django 3.2.4 on 2023-01-26 20:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0007_messageroom_users_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='seen_by_users',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Message_seen', to=settings.AUTH_USER_MODEL),
        ),
    ]
