# Generated by Django 3.2.4 on 2023-02-08 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0008_message_seen_by_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageroom',
            name='users_active',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='MessageReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction', models.CharField(choices=[('Smile', 'Smile'), ('Funny', 'Funnny'), ('Angry', 'Angry'), ('Sad', 'Sad'), ('Crying', 'Crying'), ('Heart', 'Heart')], max_length=100)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User_reaction', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'MessageReaction',
                'verbose_name_plural': 'MessageReactions',
            },
        ),
    ]
