# Generated by Django 4.1.7 on 2023-02-15 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0015_userprofile_address_userprofile_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Message_receiver', to='chat.userprofile'),
        ),
        migrations.AlterField(
            model_name='message',
            name='seen_by_users',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Message_seen', to='chat.userprofile'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Message_sender', to='chat.userprofile'),
        ),
        migrations.AlterField(
            model_name='messagereaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User_reaction', to='chat.userprofile'),
        ),
        migrations.AlterField(
            model_name='messageroom',
            name='first_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_user', to='chat.userprofile'),
        ),
        migrations.AlterField(
            model_name='messageroom',
            name='second_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_user', to='chat.userprofile'),
        ),
        migrations.AlterField(
            model_name='messageroom',
            name='users_active',
            field=models.ManyToManyField(to='chat.userprofile'),
        ),
    ]
