# Generated by Django 4.1.7 on 2023-02-18 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0019_alter_notification_from_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': 'Notification', 'verbose_name_plural': 'Notifications'},
        ),
    ]
