# Generated by Django 4.1.7 on 2023-02-20 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0021_message_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='block_users',
            field=models.ManyToManyField(blank=True, related_name='blocked_users', to='chat.userprofile'),
        ),
    ]
