# Generated by Django 4.1.7 on 2023-02-21 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0023_messagegroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageroom',
            name='one_to_one',
            field=models.BooleanField(default=True),
        ),
    ]
