# Generated by Django 4.1.7 on 2023-02-21 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0024_messageroom_one_to_one'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageroom',
            name='message_group',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.messagegroup'),
        ),
    ]
