# Generated by Django 4.1.7 on 2023-02-21 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0025_messageroom_message_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messageroom',
            name='message_group',
        ),
        migrations.AddField(
            model_name='messageroom',
            name='group_admin',
            field=models.ManyToManyField(null=True, related_name='group_admins', to='chat.userprofile'),
        ),
        migrations.DeleteModel(
            name='MessageGroup',
        ),
    ]
