# Generated by Django 4.1.7 on 2023-02-22 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0027_remove_messageroom_group_admin_messagegroup_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messageroom',
            name='group',
        ),
        migrations.AddField(
            model_name='messageroom',
            name='group',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_groups', to='chat.messagegroup'),
        ),
    ]
