# Generated by Django 4.1.7 on 2023-02-22 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0028_remove_messageroom_group_messageroom_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagegroup',
            name='group_admin',
        ),
        migrations.AddField(
            model_name='messagegroup',
            name='group_admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_admins', to='chat.userprofile'),
        ),
    ]
