# Generated by Django 4.1.7 on 2023-03-01 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0032_remove_messageroom_second_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='message',
            name='seen_by_users',
        ),
        migrations.AddField(
            model_name='message',
            name='receiver',
            field=models.ManyToManyField(related_name='Message_receiver', to='chat.userprofile'),
        ),
        migrations.AddField(
            model_name='message',
            name='seen_by_users',
            field=models.ManyToManyField(null=True, related_name='Message_seen', to='chat.userprofile'),
        ),
    ]
